FROM nginx:alpine

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

VOLUME [ "/usr/share/nginx/html" ]

RUN groupadd -r frontend && useradd -r -g frontend frontend
RUN chown -R frontend:frontend /usr/share/nginx/html
USER frontend

CMD ["./command.sh"]

